version: '3.8'

services:
  backend:
    image: ghcr.io/simonwep/genesis:v0.2
    restart: unless-stopped
    networks:
      - ocular
    volumes:
      - ./data:/app/.data
    environment:
      - GENESIS_PORT
      - GENESIS_DB_PATH
      - GENESIS_CREATE_USERS
      - GENESIS_AUTHORIZED_URIS
      - GENESIS_JWT_SECRET
      - GENESIS_JWT_TOKEN_EXPIRATION
      - GENESIS_USERNAME_PATTERN
      - GENESIS_KEY_PATTERN
      - GENESIS_DATA_MAX_SIZE
      - GENESIS_KEYS_PER_USER
      - GENESIS_GIN_MODE
      - GENESIS_LOG_MODE

  frontend:
    image: ghcr.io/simonwep/ocular:v1.3.1
    restart: unless-stopped
    networks:
      - ocular

  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    networks:
      - ocular
    ports:
      - "3030:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

networks:
  ocular:
    driver: bridge
